# Generated by Django 4.1.3 on 2022-11-16 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceType',
            new_name='ServiceTypeModel',
        ),
    ]
