# Generated by Django 4.1.3 on 2022-11-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_rename_service_type_servicemodel_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetypemodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
