# Generated by Django 4.1.3 on 2022-11-17 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicetypemodel_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='service',
            new_name='service_id',
        ),
    ]
