# Generated by Django 4.1.3 on 2022-11-17 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rename_customer_ordermodel_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='servicemodel',
            old_name='type_id',
            new_name='type',
        ),
    ]
